apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    path: manifests
    repoURL: http://192.168.56.110:8080/root/jperez.git
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev

