global:
  hosts:
    domain: localhost
    https: false
  ingress:
    configureCertmanager: false
    tls: {}
    class: gitlab-nginx
certmanager:
  install: false
gitlab:
  nginx:
    listen_https: false
gitlab-runner:
  install: false

