Vagrant.configure("2") do |config|
  ip = "192.168.56.110"

  config.vm.box = "generic/alpine318"
  config.vm.network "private_network", ip: ip
  config.vm.hostname = "jperezS"
  config.vm.synced_folder "confs", "/shared"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 1
  end
  config.vm.provision "shell", path: "confs/provision.sh", privileged: true

end
