Vagrant.configure("2") do |config|
  server_ip = "192.168.56.110"
  worker_ip = "192.168.56.111"
  
  config.vm.box = "generic/alpine318"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 1
  end

  # Definir el nodo Server
  config.vm.define "jperezS" do |server|
    server.vm.network "private_network", ip: server_ip
    server.vm.synced_folder "confs", "/shared"
    server.vm.provision "shell", privileged: true, path: "confs/server.sh" 
  end

  # Definir el nodo Worker
  config.vm.define "jperezSW" do |worker|
    worker.vm.network "private_network", ip: worker_ip
    worker.vm.synced_folder "confs", "/shared"
    worker.vm.provision "shell", privileged: true, path: "confs/worker.sh", args: [server_ip]

  end

end

